/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppStaffRouteImport } from './routes/app.staff'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRemindersRouteImport } from './routes/app.reminders'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppPatientsRouteImport } from './routes/app.patients'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppLandingEditorRouteImport } from './routes/app.landing-editor'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppDoctorsRouteImport } from './routes/app.doctors'
import { Route as AppDentalChartRouteImport } from './routes/app.dental-chart'
import { Route as AppAppointmentsRouteImport } from './routes/app.appointments'
import { Route as ApiLandingUploadRouteImport } from './routes/api/landing-upload'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'
import { Route as ApiPublicHooksProcessScheduledRouteImport } from './routes/api/public/hooks/process-scheduled'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppLandingEditorRoute = AppLandingEditorRouteImport.update({
  id: '/landing-editor',
  path: '/landing-editor',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorsRoute = AppDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppDentalChartRoute = AppDentalChartRouteImport.update({
  id: '/dental-chart',
  path: '/dental-chart',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const ApiLandingUploadRoute = ApiLandingUploadRouteImport.update({
  id: '/api/landing-upload',
  path: '/api/landing-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessScheduledRoute =
  ApiPublicHooksProcessScheduledRouteImport.update({
    id: '/api/public/hooks/process-scheduled',
    path: '/api/public/hooks/process-scheduled',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/landing-upload': typeof ApiLandingUploadRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/dental-chart': typeof AppDentalChartRoute
  '/app/doctors': typeof AppDoctorsRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/landing-editor': typeof AppLandingEditorRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hooks/process-scheduled': typeof ApiPublicHooksProcessScheduledRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/api/landing-upload': typeof ApiLandingUploadRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/dental-chart': typeof AppDentalChartRoute
  '/app/doctors': typeof AppDoctorsRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/landing-editor': typeof AppLandingEditorRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app': typeof AppIndexRoute
  '/api/public/hooks/process-scheduled': typeof ApiPublicHooksProcessScheduledRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/api/landing-upload': typeof ApiLandingUploadRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/dental-chart': typeof AppDentalChartRoute
  '/app/doctors': typeof AppDoctorsRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/landing-editor': typeof AppLandingEditorRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/': typeof AppIndexRoute
  '/api/public/hooks/process-scheduled': typeof ApiPublicHooksProcessScheduledRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/api/landing-upload'
    | '/app/appointments'
    | '/app/dental-chart'
    | '/app/doctors'
    | '/app/expenses'
    | '/app/inventory'
    | '/app/landing-editor'
    | '/app/leads'
    | '/app/notifications'
    | '/app/patients'
    | '/app/payments'
    | '/app/reminders'
    | '/app/reports'
    | '/app/settings'
    | '/app/staff'
    | '/app/'
    | '/api/public/hooks/process-scheduled'
    | '/api/public/hooks/send-reminders'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/api/landing-upload'
    | '/app/appointments'
    | '/app/dental-chart'
    | '/app/doctors'
    | '/app/expenses'
    | '/app/inventory'
    | '/app/landing-editor'
    | '/app/leads'
    | '/app/notifications'
    | '/app/patients'
    | '/app/payments'
    | '/app/reminders'
    | '/app/reports'
    | '/app/settings'
    | '/app/staff'
    | '/app'
    | '/api/public/hooks/process-scheduled'
    | '/api/public/hooks/send-reminders'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/api/landing-upload'
    | '/app/appointments'
    | '/app/dental-chart'
    | '/app/doctors'
    | '/app/expenses'
    | '/app/inventory'
    | '/app/landing-editor'
    | '/app/leads'
    | '/app/notifications'
    | '/app/patients'
    | '/app/payments'
    | '/app/reminders'
    | '/app/reports'
    | '/app/settings'
    | '/app/staff'
    | '/app/'
    | '/api/public/hooks/process-scheduled'
    | '/api/public/hooks/send-reminders'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiLandingUploadRoute: typeof ApiLandingUploadRoute
  ApiPublicHooksProcessScheduledRoute: typeof ApiPublicHooksProcessScheduledRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reminders': {
      id: '/app/reminders'
      path: '/reminders'
      fullPath: '/app/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patients': {
      id: '/app/patients'
      path: '/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/landing-editor': {
      id: '/app/landing-editor'
      path: '/landing-editor'
      fullPath: '/app/landing-editor'
      preLoaderRoute: typeof AppLandingEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/doctors': {
      id: '/app/doctors'
      path: '/doctors'
      fullPath: '/app/doctors'
      preLoaderRoute: typeof AppDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dental-chart': {
      id: '/app/dental-chart'
      path: '/dental-chart'
      fullPath: '/app/dental-chart'
      preLoaderRoute: typeof AppDentalChartRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/landing-upload': {
      id: '/api/landing-upload'
      path: '/api/landing-upload'
      fullPath: '/api/landing-upload'
      preLoaderRoute: typeof ApiLandingUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-scheduled': {
      id: '/api/public/hooks/process-scheduled'
      path: '/api/public/hooks/process-scheduled'
      fullPath: '/api/public/hooks/process-scheduled'
      preLoaderRoute: typeof ApiPublicHooksProcessScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppDentalChartRoute: typeof AppDentalChartRoute
  AppDoctorsRoute: typeof AppDoctorsRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLandingEditorRoute: typeof AppLandingEditorRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppDentalChartRoute: AppDentalChartRoute,
  AppDoctorsRoute: AppDoctorsRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLandingEditorRoute: AppLandingEditorRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiLandingUploadRoute: ApiLandingUploadRoute,
  ApiPublicHooksProcessScheduledRoute: ApiPublicHooksProcessScheduledRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
